apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-deployement
spec:
  selector:
    matchLabels:
      app: cart-service
  template:
    metadata:
      labels:
        app: cart-service
    
    spec:
      containers:
        - name: cart-container
          image: santhosh0476/cart-service
          ports:
             - containerPort: 4001