apiVersion: v1
kind: Service
metadata:
  name: product-service

spec:
  type: ClusterIP   # internal communication
  selector:
    app: product-service

  ports:
    - port: 4000
      targetPort: 4000